# Generated by Django 4.2.2 on 2023-06-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_sleeping',
            field=models.BooleanField(default=False),
        ),
    ]
